In [ ]:
#task 1 - enter 4 numbers

# get numbers - not no validation 
num1 = input("Enter a number") 
num2 = input("And another")
num3 = input("And another")
num4 = input("And your final number")


# write them
with open("Numbers.txt","w") as numFile:
    numFile.write( (num1 + "\n" + num2 + "\n" + num3 + '\n'+ num4))
numFile.close()

# read them back and display
with open("Numbers.txt","r") as f:
    data = f.read()
f.close()

print(numFile.name + " contains:\n" + data)

extraNumber = input("Enter another")

# append another number
with open("Numbers.txt","a") as f:
    data = f.write(extraNumber)
f.close()

with open("Numbers.txt","r") as f:
    data = f.read()
f.close()

print(numFile.name + " contains:\n" + data)









In [ ]:
#task 2 + extension - get studnt to enter percentage mark and convert to grade

def mark_grade(percentage):

    if percentage > 80: return 'A'
    elif percentage > 70: return 'B'
    elif percentage > 60: return 'C'
    elif percentage > 50: return 'D'
    elif percentage > 40: return 'E'
    else: return 'U'

studentPercentage = int(input("What is your percentage?"))
studentTarget = input("What was your target?")
studentGrade = mark_grade(studentPercentage)

if (studentGrade > studentTarget.upper()): print ("try harder, your grade is " + studentGrade)
elif (studentGrade == studentTarget.upper()): print ("well done you're on target grade is " + studentGrade)
else : print ("excellent you're above target, your grade is " + studentGrade)





In [ ]:
# Numpy task 1
# 1d array of numbers
import numpy as np

numArray = np.arange(10)

print(numArray)


In [ ]:
# Numpy task 2
# 3 by 3 array of bool true
import numpy as np
numArray = np.full((3,3), True)

print(numArray)

In [54]:
# Numpy task 3
# extract odd numbers from array 1 -10
import numpy as np
numArray = np.arange(1,11)
numArray = numArray[numArray % 2 == 1]

print(numArray)

[1 3 5 7 9]


In [56]:
# Numpy task 4
# replace all odd numbers from array 1 -10 with -1
import numpy as np
numArray = np.arange(1,11)
numArray = np.where(numArray % 2 ==1, -1, numArray)

print(numArray)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [63]:
# Numpy task 5
# 1d to 2 d array
import numpy as np
numArray = np.arange(14)
print("\n1D:\n",numArray)

num2D = numArray.reshape(7,2)

print("\n2D:\n", num2D)


1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]

2D:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


In [92]:
# Numpy task 6

import numpy as np
# create arrays a and b

arrayA = np.arange(6)
arrayB = np.arange(6)

# stack vertically
arrayC = np.vstack((arrayA, arrayB))
print ("A:\n",arrayA)
print ("B:\n",arrayB)
print("Stacked arrays\n", arrayC)

# mult
dotProd = np.dot(arrayA, arrayB)
print("Product:\n", dotProd)


# sum
sumArray = np.sum(arrayC)
print("Sum\n", sumArray)



A:
 [0 1 2 3 4 5]
B:
 [0 1 2 3 4 5]
Stacked arrays
 [[0 1 2 3 4 5]
 [0 1 2 3 4 5]]
Product:
 55
Sum
 30


In [107]:
#extension 1 
#create array 111,222,333,1,2,3,1,2,3,1,2,3

# this seems long winded - is there a better way?
ar1 = np.arange(1,4)
ar2 = np.hstack((ar1,ar1,ar1))
ar3 = np.vstack((ar1,ar1,ar1))
ar4 = np.reshape(ar3, 9, 'F')

ar5 = np.concatenate((ar4,ar2))

print(ar5)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [33]:
#extension 2
#setup arrays 1-5 and 4-9
import numpy as np
arA = np.arange(1,6)
arB = np.arange(4,10)
tempList = []

''' remove repeating items present in array b '''

arB = np.setdiff1d(arB,arA)

''' first attempt - then found setdiff1d
for i in arB:
    if i not in arA:
        tempList.append(i)

arB = np.array(tempList)
'''

print(arB)




[6 7 8 9]


In [67]:
#task 7
# #get all items between 3 and 7 from a and b and sum the together
import numpy as np
arA = np.arange(1,6)
arB = np.arange(4,10)
arC = np.concatenate((arA,arB))
indices = np.where(np.logical_and(arC >= 3,arC <= 7))

print("Values between 3 and 7:\n",arC[indices],"\n")
print("Sum is:\n",np.sum(arC[indices]))






Values between 3 and 7:
 [3 4 5 4 5 6 7] 

Sum is:
 34
